[build]
command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter precache
    flutter config --enable-web
    flutter build web --release
  """
publish = "build/web"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200