[build]
command = """
    curl -fsSL https://get.puro.dev/install.sh | sh
    export PATH="$PATH:$HOME/.puro/bin"
    puro install flutter --system
    export PATH="$PATH:$HOME/.puro/envs/flutter/flutter/bin"
    flutter config --enable-web
    flutter build web --release
  """
publish = "build/web"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200